fix flaky test in SentinelConfigTest
alibaba/Sentinel pull request #1884
Opened 2020-12-07 06:54 UTC by zcai2

<!--  Thanks for submitting a pull request! Here are some tips for you:

### Describe what this PR does / why we need it

Fixed flaky test testDefaultConfig that caused by testColdFactoryLargerThanOne in SentinelConfigTest

If we run testColdFactoryLargerThanOne first, it will modify SentinelConfig.COLD_FACTOR.
Then when we run testDefaultConfig, the code assertEquals(SentinelConfig.DEFAULT_CHARSET, SentinelConfig.charset()) will have issue.

The flaky tests are found by running https://github.com/idflakies/iDFlakies

### Does this pull request fix one issue?

### Describe how you did it

Set a before and after method to set the variables to the default value.

### Describe how to verify it

### Special notes for reviews

2020-12-16 01:52 UTC, sczyh30 requested changes

2020-12-16 01:52 UTC, sczyh30 commented on sentinel-core/src/test/java/com/alibaba/csp/sentinel/config/SentinelConfigTest.java
> +        SentinelConfig.setConfig(SentinelConfig.COLD_FACTOR, SentinelConfig.DEFAULT_CHARSET);
The default value should be `DEFAULT_COLD_FACTOR`.

2020-12-28 06:05 UTC, sczyh30 commented
Any feedback?

2021-01-24 14:02 UTC, zhengpengGitHub commented
test

2021-01-25 01:23 UTC, sczyh30 commented
Closing the issue due to no further feedback.

2021-01-25 01:23 UTC, closed without merging