解决Dashboard丢失间隔时间的问题
alibaba/Sentinel pull request #2171
Opened 2021-04-28 03:05 UTC by nimeijian

### Describe what this PR does / why we need it
解决从1.7.1 Tag Dashboard中的网关流控页面设置间隔时间存储至配置中心(如Apollo)并再次从配置中心读取时转换为GatewayFlowRule后丢失间隔时间的问题。

### Does this pull request fix one issue?

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2021-04-28 03:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/Sentinel?pullRequest=2171) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/Sentinel?pullRequest=2171) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/Sentinel?pullRequest=2171) it.</sub>

2021-04-28 05:39 UTC, sczyh30 requested changes

2021-04-28 05:39 UTC, sczyh30 commented on sentinel-adapter/sentinel-api-gateway-adapter-common/src/main/java/com/alibaba/csp/sentinel/adapter/gateway/common/rule/GatewayFlowRule.java
> +    private Long interval;
This may bring breaking changes (and also not necessary). Refer https://github.com/alibaba/Sentinel/pull/869#discussion_r298020134

2021-04-28 05:40 UTC, sczyh30 commented
Actually you may just leverage `GatewayFlowRuleEntity#toGatewayFlowRule` when publishing rules:

https://github.com/alibaba/Sentinel/blob/0d22aca5918f40668a9998ac134b0d3a5e2cbe6c/sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/datasource/entity/gateway/GatewayFlowRuleEntity.java#L100-L164

2021-05-06 05:48 UTC, closed without merging

2022-05-17 12:04 UTC, 1327681842 commented
> Actually you may just leverage `GatewayFlowRuleEntity#toGatewayFlowRule` when publishing rules:
> 
> https://github.com/alibaba/Sentinel/blob/0d22aca5918f40668a9998ac134b0d3a5e2cbe6c/sentinel-dashboard/src/main/java/com/alibaba/csp/sentinel/dashboard/datasource/entity/gateway/GatewayFlowRuleEntity.java#L100-L164

当冲nacos中查询到规则时返回给页面，在使用GatewayFlowRuleEntity#fromGatewayFlowFule转换回GatewayFlowRuleEntity实体吗？