fix(DynamicSentinelProperty): Fix DynamicSentinelProperty ConcurrentM…
alibaba/Sentinel pull request #2510
Opened 2021-12-24 11:27 UTC by zhangyunan1994

### Describe what this PR does / why we need it

使用 Iterator 来解决  https://github.com/alibaba/Sentinel/issues/2497 中提到的并发更新问题

### Does this pull request fix one issue?

Fix #2497 

### Describe how you did it

采用 Iterator 和 removeif 来解决并发更新问题，将 updateValue和removeListener 两个方法改为使用迭代器处理

### Describe how to verify it

### Special notes for reviews

2021-12-27 05:53 UTC, sczyh30 requested changes

2021-12-27 05:53 UTC, sczyh30 commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/property/DynamicSentinelProperty.java
> +        Iterator<PropertyListener<T>> iterator = listeners.iterator();
This does not solve the problem. The original "for-each" code already leverages the iterator, which must be synchronized by the caller. It's recommended to replace `Collections.synchronizedSet` with another concurrent set.

2021-12-28 09:11 UTC, zhangyunan1994 commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/property/DynamicSentinelProperty.java
> +        Iterator<PropertyListener<T>> iterator = listeners.iterator();
是的，这样改没有解决问题。我再看下代码，看看是否可以通过加锁或者换其他的 Set 来解决这个问题

2021-12-28 09:12 UTC, zhangyunan1994 commented
我先 close 这个 pr, 然后尝试一下其他的修改

2021-12-28 09:12 UTC, closed without merging