新增 csp.sentinel.log.level 启动配置项，可设置为OFF，进行关闭日志
alibaba/Sentinel pull request #2514
Opened 2021-12-28 07:17 UTC by zhaoxinhu

对应issues：Add record log level configuration support | 支持配置 record 日志的输出级别配置 #2505
通过添加启动配置项 csp.sentinel.log.level=OFF，可以选择性的关闭产生的日志

2021-12-28 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/Sentinel?pullRequest=2514) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/Sentinel?pullRequest=2514) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/Sentinel?pullRequest=2514) it.</sub>

2022-01-04 06:11 UTC, zhaoxinhu commented
第一次贡献源代码，这个pr是有问题合并不了？还是需要审批流程？

2022-01-04 15:33 UTC, brotherlu-xcq requested changes

2022-01-04 15:33 UTC, brotherlu-xcq commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java
> +        if (!LogBase.getLogLevel().equals(Level.OFF)) {
metric的写日志逻辑实际已经通过`csp.sentinel.metric.flush.interval`参数进行控制了，这个日志打印我觉得更应该在日志层面调用去控制，而不是通过日志级别来控制metricTimerListener的启用。

2022-01-05 01:23 UTC, zhaoxinhu commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java
> +        if (!LogBase.getLogLevel().equals(Level.OFF)) {
好的，明白了，我调整一下

2022-01-10 05:52 UTC, sczyh30 commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRuleManager.java
> +import java.util.logging.Level;
Could you please remove the unused import?

2022-01-10 05:52 UTC, sczyh30 commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/log/LogBase.java
> +            logLevel = Level.parse(logLevelString);
What if the logLevel is invalid?

2022-01-13 05:54 UTC, sczyh30 commented
Could you please sign the CLA here: https://cla-assistant.io/alibaba/Sentinel?pullRequest=2514

2022-01-13 07:50 UTC, sczyh30 commented
cc @brotherlu-xcq Any other suggestions?

2022-01-13 10:16 UTC, brotherlu-xcq commented
> cc @brotherlu-xcq Any other suggestions?

I have no more suggestions. LGTM

2022-01-14 09:02 UTC, brotherlu-xcq approved these changes
LGTM

2022-01-14 09:22 UTC, merged

2022-01-14 09:22 UTC, sczyh30 commented
Thanks for contributing!