提供spring的全局异常处理器，会导致熔断规则(异常数规则)失效解决方案
alibaba/Sentinel pull request #2516
Opened 2021-12-31 03:40 UTC by roy500

### Describe what this PR does / why we need it
srntinel-spring-webmvc-adapter使用HandlerInterceptor做异常统计等处理，但在实际开发中都会用@ControllerAdvice全局异常处理如下：
![image](https://user-images.githubusercontent.com/24887350/147801857-044f8c39-0d43-4933-8f81-5d1340b2731f.png)

因为拦截顺序会按照controller -> aspect -> controllerAdvice -> interceptor -> filter往下走，这导致异常已在ControllerAdvice被捕获处理，HandlerInterceptor无法统计异常

### Does this pull request fix one issue?

Fixes #2461

### Describe how you did it
在AbstractSentinelInterceptor下添加与afterCompletion处理相同的方法exceptionControllerAdviceExit，提供给全局异常捕获类调用如下：
![image](https://user-images.githubusercontent.com/24887350/147801570-686d39d6-5d57-4e72-bab4-c8efc1879387.png)
![image](https://user-images.githubusercontent.com/24887350/147801691-e1c1b3b9-79de-4015-837c-52a4873910a4.png)
这样就可以捕获系统异常，自定义的业务异常也是同样调用，这里也不用担心会统计两次afterCompletion下的increaseReferece做了判断
### Describe how to verify it
只要定义异常捕获处理都无法对异常进行统计，业务异常也是如此
![image](https://user-images.githubusercontent.com/24887350/147801852-97cf62f7-f4e9-4918-8028-6cb9afaa883e.png)

### Special notes for reviews

2022-01-10 01:25 UTC, roy500 commented
这么还没审核，是有什么问题嘛 @sczyh30 @cdfive

2022-01-10 03:10 UTC, roy500 commented
@sczyh30  我并没有修改sentinel-demo-spring-webflux项目代码，build报错Could not resolve dependencies for project com.alibaba.csp:sentinel-demo-spring-webflux:jar:1.8.3: Could not find artifact com.alibaba.csp:spring-boot-starter-ahas-sentinel-client:jar:1.10.5-SNAPSHOT，master版本也还是sentinel-demo-spring-webflux:jar:1.8.2，这是为什么

2022-01-10 03:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/Sentinel?pullRequest=2516) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/Sentinel?pullRequest=2516) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/Sentinel?pullRequest=2516) it.</sub>

2022-01-10 03:41 UTC, roy500 commented
@sczyh30 因为没用合并1.8.3版本代码导致build失败，现在已合并，麻烦重新build下

2022-01-11 13:29 UTC, brotherlu-xcq requested changes

2022-01-11 13:29 UTC, brotherlu-xcq commented on sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/AbstractSentinelInterceptor.java
> + * deal with the initial request. So we use <b>reference count</b> to track in
maybe not change the code indent is better. bellow is same.

2022-01-12 01:08 UTC, roy500 commented on sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/AbstractSentinelInterceptor.java
> + * deal with the initial request. So we use <b>reference count</b> to track in
已提交

2022-01-12 02:47 UTC, brotherlu-xcq commented on sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/AbstractSentinelInterceptor.java
> +
seem still have this problem.

2022-01-12 03:06 UTC, roy500 commented on sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/AbstractSentinelInterceptor.java
> +
已确认修改

2022-01-16 14:21 UTC, brotherlu-xcq approved these changes

2022-01-20 01:18 UTC, roy500 commented
@sczyh30 You can continue to review

2022-01-20 15:50 UTC, brotherlu-xcq commented
The handler can be invoked when we have a global exception handler in your code. the process logic in spring mvc when we have an Exception like bellow. I think we have more disscuss on this issue.
```java
	private void processDispatchResult(HttpServletRequest request, HttpServletResponse response,
			@Nullable HandlerExecutionChain mappedHandler, @Nullable ModelAndView mv,
			@Nullable Exception exception) throws Exception {

		boolean errorView = false;

		if (exception != null) {
			if (exception instanceof ModelAndViewDefiningException) {
				logger.debug("ModelAndViewDefiningException encountered", exception);
				mv = ((ModelAndViewDefiningException) exception).getModelAndView();
			}
			else {
				Object handler = (mappedHandler != null ? mappedHandler.getHandler() : null);

                                 // the logic invoke our global exception handler.
				mv = processHandlerException(request, response, handler, exception);
				errorView = (mv != null);
			}
		}

		// Did the handler return a view to render?
		if (mv != null && !mv.wasCleared()) {
			render(mv, request, response);
			if (errorView) {
				WebUtils.clearErrorRequestAttributes(request);
			}
		}
		else {
			if (logger.isTraceEnabled()) {
				logger.trace("No view rendering, null ModelAndView returned.");
			}
		}

		if (WebAsyncUtils.getAsyncManager(request).isConcurrentHandlingStarted()) {
			// Concurrent handling started during a forward
			return;
		}

                // the interceptor can be invoked. but the exception lost.
		if (mappedHandler != null) {
			mappedHandler.triggerAfterCompletion(request, response, null);
		}
	}
```

2022-01-21 06:17 UTC, roy500 commented
> 当我们在您的代码中有一个全局异常处理程序时，可以调用该处理程序。当我们遇到如下异常时，spring mvc 中的流程逻辑。我认为我们需要就这个问题进行更多的讨论。
> 
> ```java
> 	private  void processDispatchResult（HttpServletRequest请求，HttpServletResponse响应，
> 			 @Nullable HandlerExecutionChain  mappedHandler，@Nullable  ModelAndView mv，
> 			 @Nullable  Exception异常）抛出异常{
> 
> 		布尔错误视图= 假；
> 
> 		if (exception !=  null ) {
> 			 if (exception instanceof  ModelAndViewDefiningException ) {
> 				记录器。debug( "遇到ModelAndViewDefiningException " ,异常);
> 				mv = (( ModelAndViewDefiningException ) 异常) 。获取模型和视图（）；
> 			}
> 			else {
> 				对象处理程序= (mappedHandler !=  null  ? mappedHandler . getHandler() :  null );
> 
>                                  //逻辑调用我们的全局异常处理程序。
> 				mv = processHandlerException（请求、响应、处理程序、异常）；
> 				errorView = (mv !=  null );
> 			}
> 		}
> 
> 		//处理程序是否返回要渲染的视图？
> 		if (mv !=  null  &&  ! mv . wasCleared()) {
> 			渲染（MV，请求，响应）；
> 			if (errorView) {
> 				 WebUtils . clearErrorRequestAttributes(request);
> 			}
> 		}
> 		否则{
> 			 if (logger . isTraceEnabled()) {
> 				记录器。trace( "没有视图渲染，返回 null ModelAndView。" );
> 			}
> 		}
> 
> 		if ( WebAsyncUtils . getAsyncManager(request) . isConcurrentHandlingStarted()) {
> 			 //
> 			在前向返回期间开始并发处理;
> 		}
> 
>                 //可以调用拦截器。但异常丢失了。
> 		if (mappedHandler !=  null ) {
> 			映射处理程序。triggerAfterCompletion(request, response, null );
> 		}
> 	}
> ```

是可以通过重写processDispatchResult将exception传递下去，但需要自定义DispatcherServlet
`// the interceptor can be invoked. but the exception lost.
		if (mappedHandler != null) {
			//mappedHandler.triggerAfterCompletion(request, response, exception);
		}`

2022-01-21 06:20 UTC, roy500 commented
> The handler can be invoked when we have a global exception handler in your code. the process logic in spring mvc when we have an Exception like bellow. I think we need have more disscuss on this issue.
> 
> ```java
> 	private void processDispatchResult(HttpServletRequest request, HttpServletResponse response,
> 			@Nullable HandlerExecutionChain mappedHandler, @Nullable ModelAndView mv,
> 			@Nullable Exception exception) throws Exception {
> 
> 		boolean errorView = false;
> 
> 		if (exception != null) {
> 			if (exception instanceof ModelAndViewDefiningException) {
> 				logger.debug("ModelAndViewDefiningException encountered", exception);
> 				mv = ((ModelAndViewDefiningException) exception).getModelAndView();
> 			}
> 			else {
> 				Object handler = (mappedHandler != null ? mappedHandler.getHandler() : null);
> 
>                                  // the logic invoke our global exception handler.
> 				mv = processHandlerException(request, response, handler, exception);
> 				errorView = (mv != null);
> 			}
> 		}
> 
> 		// Did the handler return a view to render?
> 		if (mv != null && !mv.wasCleared()) {
> 			render(mv, request, response);
> 			if (errorView) {
> 				WebUtils.clearErrorRequestAttributes(request);
> 			}
> 		}
> 		else {
> 			if (logger.isTraceEnabled()) {
> 				logger.trace("No view rendering, null ModelAndView returned.");
> 			}
> 		}
> 
> 		if (WebAsyncUtils.getAsyncManager(request).isConcurrentHandlingStarted()) {
> 			// Concurrent handling started during a forward
> 			return;
> 		}
> 
>                 // the interceptor can be invoked. but the exception lost.
> 		if (mappedHandler != null) {
> 			mappedHandler.triggerAfterCompletion(request, response, null);
> 		}
> 	}
> ```

是可以通过重写processDispatchResult将exception 传递下去，这样interceptor 就能统计异常，但需要自定义DispatcherServlet
![image](https://user-images.githubusercontent.com/24887350/150476587-5f6f34dd-ca50-440b-9907-f5a34c0230ae.png)

2022-01-21 10:37 UTC, brotherlu-xcq commented
@roy500 前面本来通过我们自定的ExceptionHandler将异常处理掉，封装为ModelAndView，如果重写DispatcherServlet，手动补上了exception，再将异常抛给interceptor处理，这就有违设计者的初衷了。
现在的这种方式，虽然会执行两次afterComplete，但是由于preHandle的时候往requestHeader里面添加资源和次数，所以暂时还没有问题。但是你现在这种实现方式用户使用起来太复杂了，我建议我们最好可以把afterComplete的逻辑抽一份出来放到一个特定的class里面，定义一个静态方法，说明专门是提供给这种场景使用的，这样可能会好一点。你觉得呢？

2022-01-24 06:27 UTC, roy500 commented
@brotherlu-xcq 已修改

2022-01-24 06:31 UTC, brotherlu-xcq commented
The CI failed, could you check it first?

2022-01-25 02:19 UTC, roy500 commented
@brotherlu-xcq brother lu 已修改，编译通过

2022-01-25 03:19 UTC, brotherlu-xcq requested changes

2022-01-25 03:19 UTC, brotherlu-xcq commented on sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/SentinelAfterException.java
> +public class SentinelAfterException {
类的命名我觉得用Helper或者Util之类结尾话的更合理些。Exception结尾看着像是一个异常类。

2022-01-25 03:19 UTC, brotherlu-xcq commented on sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/SentinelAfterException.java
> +        abstractSentinelInterceptor.afterCompletion(request, null, null, ex);
你应该是为了把逻辑收拢到一起，复用abstractSentinelInterceptor的逻辑.但是这样使用的话需要依赖abstractSentinelInterceptor反向注入实例对象，这样感觉不是很合理。我觉得完全可以把abstractSentinelInterceptor中的enter和exit的逻辑抽离到这个类中。abstractSentinelInterceptor来调用这个类的方法，这样逻辑收拢了。调用也合理些。

2022-01-25 03:19 UTC, brotherlu-xcq commented on sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/SentinelAfterException.java
> +package com.alibaba.csp.sentinel.adapter.spring.webmvc;
需要添加一下license

2022-01-25 10:35 UTC, roy500 commented on sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/SentinelAfterException.java
> +        abstractSentinelInterceptor.afterCompletion(request, null, null, ex);
因为abstractSentinelInterceptor抽象类有两个父类SentinelWebInterceptor和SentinelWebTotalInterceptor，初始化BaseWebMvcConfig不是一致的。如果afterCompletion逻辑抽离成静态方法，会变得十分麻烦导致编译错误

2022-01-27 01:44 UTC, roy500 commented
@brotherlu-xcq 帮忙重新build下

2022-01-27 02:27 UTC, brotherlu-xcq commented on sentinel-adapter/sentinel-spring-webmvc-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/spring/webmvc/SentinelAfterException.java
> +        abstractSentinelInterceptor.afterCompletion(request, null, null, ex);
@sczyh30 这个有好的建议吗？

2022-01-27 02:31 UTC, brotherlu-xcq commented
CI 失败了

2022-01-27 02:40 UTC, roy500 commented
@brotherlu-xcq 但是我并没有修改到编译失败的项目，之前也有这样的情况，还请帮忙看下
![image](https://user-images.githubusercontent.com/24887350/151282098-84ec220f-86cc-42da-a000-1d6e9f7ca240.png)

2022-01-27 03:29 UTC, roy500 commented
@brotherlu-xcq 我拉取合并了最新代码，麻烦再build下

2022-01-28 06:25 UTC, roy500 commented
@sczyh30 @brotherlu-xcq It's ready for review

2022-02-11 01:25 UTC, roy500 commented
@brotherlu-xcq @sczyh30 It's ready for review

2022-03-10 01:42 UTC, roy500 commented
@sczyh30 @brotherlu-xcq  It's been placing for a long time

2022-03-28 04:19 UTC, brucelwl commented
根本不需要这么复杂去处理这个问题，如果你是SpringBoot工程，SpringBoot2.x默认会在HttpServletRequest中添加一个名为``org.springframework.boot.web.servlet.error.DefaultErrorAttributes.ERROR``的数据,里面就是异常,
如果你是springboot低版本或者只是springmvc工程,可以参考SpringBoot2.x中的DefaultErrorAttributes,自定义HandlerExceptionResolver,来记录异常, 在afterCompletion中通过HttpServletRequest读取就行

2022-03-28 06:28 UTC, closed without merging