optimize BlockException log
alibaba/Sentinel pull request #2853
Opened 2022-08-29 16:15 UTC by icodening

### Describe what this PR does / why we need it
优化BlockException日志，方便了解触发阻断异常的规则

### Does this pull request fix one issue?
Fixes #2851 

### Describe how you did it
给`AbstractRule`添加id属性即可

### Describe how to verify it
配置并触发规则后即可看到id

### Special notes for reviews
<img width="478" alt="image" src="https://user-images.githubusercontent.com/42876375/187246295-7fa51615-1ae1-4de4-8b02-5169cdbf8cb0.png">

2022-08-30 02:19 UTC, brucelwl commented
@icodening 把ruleId放在, 具体exception后面是不是更加直观点, 如下格式
![image](https://user-images.githubusercontent.com/13413715/187333931-2ea145fa-14db-4568-a1d9-e2d99f978154.png)

2022-08-30 05:47 UTC, sczyh30 requested changes

2022-08-30 05:47 UTC, sczyh30 commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/logger/EagleEyeLogUtil.java
> +        statLogger.stat(String.valueOf(ruleId), resource, exceptionName, ruleLimitApp, origin).count(count);
1. ruleId 为空的时候，这里建议做空处理，不要把 null 打出来
2. 建议保持格式的兼容性，新的字段往后 append 而不是在最前面加

2022-08-30 05:47 UTC, sczyh30 commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/logger/EagleEyeLogUtil.java
> +    //TEST
Unused comment?

2022-08-30 12:45 UTC, icodening commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/logger/EagleEyeLogUtil.java
> +        statLogger.stat(String.valueOf(ruleId), resource, exceptionName, ruleLimitApp, origin).count(count);
OK 有道理 可以兼顾对于旧版本的日志采集 晚点我改一下

2022-08-31 02:31 UTC, sczyh30 approved these changes
LGTM

2022-08-31 02:32 UTC, merged

2022-08-31 02:33 UTC, sczyh30 commented
Nice work. Thanks for contributing!

2022-08-31 02:35 UTC, sczyh30 commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/logger/EagleEyeLogUtil.java
> +        statLogger.stat(String.valueOf(ruleId), resource, exceptionName, ruleLimitApp, origin).count(count);
这里面其实还有一个点，就是 ID 用 Long 类型可能不利于未来扩展，社区可能需要考虑下未来是否搞成 String 类型的。当然这里面可能会有连带影响，比如集群流控的 requestToken 的格式

2022-08-31 02:44 UTC, icodening commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/logger/EagleEyeLogUtil.java
> +        statLogger.stat(String.valueOf(ruleId), resource, exceptionName, ruleLimitApp, origin).count(count);
> 这里面其实还有一个点，就是 ID 用 Long 类型可能不利于未来扩展，社区可能需要考虑下未来是否搞成 String 类型的。当然这里面可能会有连带影响，比如集群流控的 requestToken 的格式

是的，这个问题我们也遇到了，Long ID不好扩展。我们需要在client端拼接一个ID，并不好拼成一个集群中都一致的Long ID

2022-08-31 02:45 UTC, sczyh30 commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/logger/EagleEyeLogUtil.java
> +        statLogger.stat(String.valueOf(ruleId), resource, exceptionName, ruleLimitApp, origin).count(count);
可以提个 issue 记录下哈

2022-08-31 02:50 UTC, icodening commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/logger/EagleEyeLogUtil.java
> +        statLogger.stat(String.valueOf(ruleId), resource, exceptionName, ruleLimitApp, origin).count(count);
好的  回头我记录下

2022-08-31 12:47 UTC, brucelwl commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/logger/EagleEyeLogUtil.java
> +        statLogger.stat(String.valueOf(ruleId), resource, exceptionName, ruleLimitApp, origin).count(count);
> > 这里面其实还有一个点，就是 ID 用 Long 类型可能不利于未来扩展，社区可能需要考虑下未来是否搞成 String 类型的。当然这里面可能会有连带影响，比如集群流控的 requestToken 的格式
> 
> 是的，这个问题我们也遇到了，Long ID不好扩展。我们需要在client端拼接一个ID，并不好拼成一个集群中都一致的Long ID

这里的改动其实改变了统计维度,原来是按照Exception统计的, 现在变成了按照规则维度统计打印block日志