resource rules (flow/degrade/param/authority) support regex matching
alibaba/Sentinel pull request #3251
Opened 2023-10-27 06:55 UTC by LiYangSir

### Describe what this PR does / why we need it
Resource rules support matching resource names according to regular rules, allowing users to configure traffic limiting rules or batch configuration.
When adding/deleting interfaces, there is no need to manually create/delete rules.

资源规则支持按照正则匹配资源名称，允许用户按照配置兜底限流规则或批量配置的能力。
当新增/删除接口时，无需手动创建/删除规则。

### Does this pull request fix one issue?
Fixes #3247 

### Describe how you did it
Add a RuleManger to uniformly manage ordinary rules and regular rules. In order to reduce the performance loss caused by regular parsing/matching, the following two methods are used:
1. Add a cache to cache the current limiting rules after regular parsing. When matching the current limiting rules, first search from the cache;
2. Rebuild the cache. When the current limiting rule is updated, new cache data is rebuilt based on the old cache data to reduce the performance loss caused by cache failure after the rule is updated;

增加一个 RuleManger 统一管理普通规则和正则规则，为了减少正则解析/匹配所带来的性能损耗，使用下面两种方式：
1. 增加缓存，缓存正则解析后的限流规则，匹配限流规则时先从缓存中去查找；
2. 重建缓存，当限流规则出现更新时，依据旧缓存数据重建新的缓存数据，减少由于更新规则后，缓存失效带来的性能损耗；

### Describe how to verify it

Regular unit tests have been added to each of the four rules to ensure normal performance; if regular rules are turned on, current limiting rules that meet regular matching but have different resource names will take effect.

对四种规则分别增加了正则的单元测试，用于保证表现正常；如果开启了正则规则，满足正则匹配但资源名称不同的限流规则均会生效。
1. Authority Rule：com.alibaba.csp.sentinel.slots.block.authority.AuthorityPartialIntegrationTest
2. Degrade Rule：com.alibaba.csp.sentinel.slots.block.degrade.DegradePartialIntegrationTest
4. Flow Rule：com.alibaba.csp.sentinel.slots.block.flow.FlowPartialIntegrationTest
6. Hot Pram Rule：com.alibaba.csp.sentinel.slots.block.flow.param.ParamFlowPartialIntegrationTest

### Special notes for reviews
None

2023-12-21 11:42 UTC, LearningGp requested changes

2023-12-21 11:42 UTC, LearningGp commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/RuleManager.java
> +package com.alibaba.csp.sentinel.slots.block;
Could you please prepend the license header here?

2023-12-21 11:42 UTC, LearningGp commented on sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/RuleManager.java
Could you please add unit tests for this class?

2023-12-22 05:52 UTC, LearningGp commented
It would be helpful to have a benchmark report comparing the original rules. :rocket:

2023-12-25 05:45 UTC, LiYangSir commented
> It would be helpful to have a benchmark report comparing the original rules. 🚀

### Throughput (s)
![image](https://github.com/alibaba/Sentinel/assets/50188356/57f4c32e-cc29-47fa-b05f-b693343a007b)

### Throughput (ns)
![image](https://github.com/alibaba/Sentinel/assets/50188356/b8fea0c9-e359-48fc-8574-ac30d5a4141a)

### AverageTime (ns)
![image](https://github.com/alibaba/Sentinel/assets/50188356/a8bed6b3-4f33-4343-8161-5bd737a9233a)

> ps: testNormal: Original Type; testRegex: Direct use regex parse; testRegexWitchCache: use cache regex result

Due to the need to retrieve rules from the regex cache map and regular rules, the throughput of the previous retrieval method is twice that of direct retrieval, but it is also within an acceptable range.

2023-12-26 05:42 UTC, LearningGp approved these changes
LGTM

2023-12-27 11:27 UTC, merged

2023-12-27 11:27 UTC, LearningGp commented
Thanks for contributing! 🚀