update CONTRIBUTING.md
alibaba/Sentinel pull request #3346
Opened 2024-02-22 03:33 UTC by robberphex

### Describe what this PR does / why we need it

Update CONTRIBUTING.md, describe how to run tests on different jdk version.

### Does this pull request fix one issue?

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2024-02-22 03:41 UTC, LearningGp requested changes

2024-02-22 03:41 UTC, LearningGp commented on CONTRIBUTING.md
> +1. add `~/.m2/toolchains.xml`, to define JDK and path. See [toolcahinas-example.xml](./toolcahinas-example.xml).
Typo

2024-02-22 03:50 UTC, LearningGp approved these changes
LGTM

2024-02-27 11:00 UTC, panxiaojun233 approved these changes
LGTM

2024-02-27 11:02 UTC, merged